server:
  port: ${PORT}
  servlet:
    context-path: /api/v1
spring:
  application:
    name: sinnts-grading

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database: postgresql

  flyway:
    baselineOnMigrate: true
    enabled: true
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    baselineDescription: "init"
    baselineVersion: 0

application:
  security:
    jwt:
      secretKey: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRY}
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXPIRY}